name: Staging Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - staging

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref_name == 'staging'

    steps:
      - name: Mostrar información
        run: |
          echo "Hola desde staging"
          echo "Rama: ${{ github.ref_name }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Listar archivos
        run: ls -la